# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f1027103c8afd8d4906f71c1c3b627e0ede46be9f82307ae6b796720401cafbd935a294485d0b45520f84c837dd38cf992f5748932afa033f02ef98736657de

test:
  secret_key_base: 255a40f62bb9cd53f69f70e0f5b6860096fcccb625351373fa073acbeff66ad99a0b49c1697615bcdc902225005b4ec3fd9516e04afbfde622676a8b3ea6b083

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
